# get access token

In [1]:
import os
from pathlib import Path
import sys
from dotenv import load_dotenv
# BASE_DIR = Path("$gol/hearts/daraz/discount.py").resolve().parents[1]
# sys.path.extend([
#     str(BASE_DIR / "daraz" / "iop" / "python"),
#     str(BASE_DIR / "daraz" / "sdk" / "python")
# ])
env_path = Path("/mnt/f/golem/hearts/daraz/dev/.env")
load_dotenv(env_path)
# load_dotenv()
# print(os.getenv("DARAZ_APP_KEY"))

True

In [2]:
from discount import discount
print("IN_JUPYTER:", discount.IN_JUPYTER)
print("access_token:", repr(discount.access_token))
print("token works:", discount.token_works())

import threading, traceback
print("Threads:", [(t.name, t.is_alive()) for t in threading.enumerate()])

IN_JUPYTER: True
access_token: '50000002019YzUq5qUTiIEQoVdVv9F11d9a3c8alqTbuPWpQsyZ4pbNg5zDE3z'
token works: True
Threads: [('MainThread', True), ('IOPub', True), ('Heartbeat', True), ('Thread-1 (_watch_pipe_fd)', True), ('Thread-2 (_watch_pipe_fd)', True), ('Control', True), ('IPythonHistorySavingThread', True)]

In [ ]:
print("IN_JUPYTER:", discount.IN_JUPYTER)
print("Access token already set:", discount.access_token)
print("token works:", discount.token_works())

In [3]:
1+3

4

In [ ]:
from discount import discount

access_token = discount.get_access_token()
print(access_token)

50000002019YzUq5qUTiIEQoVdVv9F11d9a3c8alqTbuPWpQsyZ4pbNg5zDE3z
Threads: [('MainThread', True), ('IOPub', True), ('Heartbeat', True), ('Thread-1 (_watch_pipe_fd)', True), ('Thread-2 (_watch_pipe_fd)', True), ('Control', True), ('IPythonHistorySavingThread', True)]

In [4]:
from discount import discount

discount.token_works()

True

In [ ]:
access_token
# 1+3

# get finance data

## full code

In [74]:
# Example usage
from iop.python import iop
url = os.getenv("DARAZ_BASE_URL", "https://api.daraz.com.bd/rest")
appkey = os.getenv("DARAZ_APP_KEY")
appSecret = os.getenv("DARAZ_APP_SECRET")
authUrl = os.getenv("DARAZ_AUTH_URL")
access_token = os.getenv("DARAZ_ACCESS_TOKEN")

client = iop.IopClient(url, appkey, appSecret)
request = iop.IopRequest('/finance/transaction/details/get', 'GET')

request.add_api_param('access_token', access_token)
# request.add_api_param('offset', '0')
# request.add_api_param('trans_type', '-1')
# request.add_api_param('trade_order_id', '684403864843903')
# request.add_api_param('limit', '500')
request.add_api_param('start_time', '2026-03-02')
request.add_api_param('end_time', '2026-03-07')
# request.add_api_param('trade_order_line_id', '45645674566')

response = client.execute(request, access_token)

# print(response.type)
data_json = response.body

In [ ]:
data_json

In [75]:
import json
data = json.loads(data_json)["data"]
# print(data)

In [76]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)
df = pd.DataFrame(data)
# df = pd.DataFrame(trans)
# df.head(100)

In [77]:
df[df['order_no'] == '684403864843903']

            order_no transaction_date  amount paid_status WHT_included_in_amount  payment_ref_id fee_type                           transaction_type        reference                     fee_name WHT_amount transaction_number                  statement comment VAT_in_amount shipping_provider               lazada_sku     orderItem_no orderItem_status shipping_speed  seller_sku                                                                                                                          details shipment_type
407  684403864843903      02 Mar 2026   -5.75        paid                     No  EFT_SCB_Mar'26      114  Services-Logistics & Fulfillment Services  684403864943903                 Handling Fee       0.00    684403864943903  02 Mar 2026 - 08 Mar 2026                  0.75               NaN                      NaN              NaN              NaN            NaN         NaN                                                                                                                              NaN           NaN
408  684403864843903      02 Mar 2026  -29.38        paid                     No  EFT_SCB_Mar'26       16          Delivered Orders-Transaction Fees  684403864943903               Commission Fee       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  3.83            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
409  684403864843903      02 Mar 2026  -70.00        paid                     No  EFT_SCB_Mar'26       28          Delivered Orders-Transaction Fees  684403864943903                 Shipping Fee       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  9.13            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
410  684403864843903      02 Mar 2026   -4.49        paid                     No  EFT_SCB_Mar'26        3          Delivered Orders-Transaction Fees  684403864943903                  Payment Fee       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  0.59            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
411  684403864843903      02 Mar 2026   70.00        paid                     No  EFT_SCB_Mar'26        8          Delivered Orders-Delivered Orders  684403864943903   Shipping Fee Paid by Buyer       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  0.00            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
412  684403864843903      02 Mar 2026  145.00        paid                     No  EFT_SCB_Mar'26       13          Delivered Orders-Delivered Orders  684403864943903  Product Price Paid by Buyer       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  0.00            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
413  684403864843903      02 Mar 2026   -5.00        paid                     No  EFT_SCB_Mar'26      298          Delivered Orders-Transaction Fees  684403864943903        Free Shipping Max Fee       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  0.65            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping
414  684403864843903      02 Mar 2026   -4.35        paid                     No  EFT_SCB_Mar'26      515          Delivered Orders-Delivered Orders  684403864943903        Co-funded Voucher Max       0.00    189159290153903  02 Mar 2026 - 08 Mar 2026                  0.00            BD-DEX  531411046_BD-2549486307  684403864943903        Delivered       standard  20250601/1  Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]  Dropshipping

In [29]:
df[df['order_no'] == '684403864843903']

            order_no transaction_date amount paid_status shipping_provider WHT_included_in_amount  payment_ref_id lazada_sku fee_type                           transaction_type orderItem_no orderItem_status        reference      fee_name shipping_speed WHT_amount transaction_number seller_sku                  statement details comment VAT_in_amount shipment_type
499  684403864843903      02 Mar 2026  -5.75        paid               NaN                     No  EFT_SCB_Mar'26        NaN      114  Services-Logistics & Fulfillment Services          NaN              NaN  684403864943903  Handling Fee            NaN       0.00    684403864943903        NaN  02 Mar 2026 - 08 Mar 2026     NaN                  0.75           NaN

In [ ]:
df[df['fee_type'] == '13']

            order_no transaction_date    amount paid_status shipping_provider WHT_included_in_amount  payment_ref_id               lazada_sku fee_type                   transaction_type     orderItem_no orderItem_status        reference                     fee_name shipping_speed WHT_amount transaction_number                                    seller_sku                  statement                                                                                                                                                                                                                                    details comment VAT_in_amount shipment_type
14   684642418417238      08 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  684642418517238        Delivered  684642418517238  Product Price Paid by Buyer       standard       0.00    189611990157238                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
25   685477720194845      08 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  685477720394845        Delivered  685477720394845  Product Price Paid by Buyer       standard       0.00    186629501154845                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
26   685477720194845      08 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685477720294845        Delivered  685477720294845  Product Price Paid by Buyer       standard       0.00    186629500154845                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
47   684627615012314      08 Mar 2026    750.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  543722020_BD-2566126475       13  Delivered Orders-Delivered Orders  684627615312314        Delivered  684627615312314  Product Price Paid by Buyer       standard       0.00    189595393152314                                    20250820/3  02 Mar 2026 - 08 Mar 2026                                                                        Premium Paper Shopping Bag with Matt Lamination (12 Pcs) – Durable & Elegant Carry Bag for Shops, Restaurants, and Gifts [ Hearts Gift Bag Smart (Mat Best Wishes)]                  0.00  Dropshipping
48   684627615012314      08 Mar 2026    750.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  543722020_BD-2566126475       13  Delivered Orders-Delivered Orders  684627615212314        Delivered  684627615212314  Product Price Paid by Buyer       standard       0.00    189595392152314                                    20250820/3  02 Mar 2026 - 08 Mar 2026                                                                        Premium Paper Shopping Bag with Matt Lamination (12 Pcs) – Durable & Elegant Carry Bag for Shops, Restaurants, and Gifts [ Hearts Gift Bag Smart (Mat Best Wishes)]                  0.00  Dropshipping
49   684627615012314      08 Mar 2026    750.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  543722020_BD-2566126475       13  Delivered Orders-Delivered Orders  684627615112314        Delivered  684627615112314  Product Price Paid by Buyer       standard       0.00    189595391152314                                    20250820/3  02 Mar 2026 - 08 Mar 2026                                                                        Premium Paper Shopping Bag with Matt Lamination (12 Pcs) – Durable & Elegant Carry Bag for Shops, Restaurants, and Gifts [ Hearts Gift Bag Smart (Mat Best Wishes)]                  0.00  Dropshipping
50   685404746519841      08 Mar 2026    450.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  530002429_BD-2558960144       13  Delivered Orders-Delivered Orders  685404746619841        Delivered  685404746619841  Product Price Paid by Buyer       standard       0.00    189595307159841                               20250505-Coffee  02 Mar 2026 - 08 Mar 2026                                                                                                                         Car Document Folder (PU Leather) – Premium Hearts Design for Vehicle Papers & Cards [ Hearts Car Document Folder ]                  0.00  Dropshipping
56   684646012870399      08 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684646012970399        Delivered  684646012970399  Product Price Paid by Buyer       standard       0.00    189591234150399                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
62   684640296654796      08 Mar 2026  1,199.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  529986845_BD-2546835092       13  Delivered Orders-Delivered Orders  684640296754796        Delivered  684640296754796  Product Price Paid by Buyer       standard       0.00    188158782154796                                20250506-Black  02 Mar 2026 - 08 Mar 2026                                                                                                        Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]                  0.00  Dropshipping
67   685462785922367      08 Mar 2026    360.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  530178133_BD-2580890201       13  Delivered Orders-Delivered Orders  685462786022367        Delivered  685462786022367  Product Price Paid by Buyer       standard       0.00    188158410152367                                    20250507/6  02 Mar 2026 - 08 Mar 2026                                                                                                                                           Journal Notebook — PU Leather, Hardcover, Elastic Band, Dotted Pages, Office/Study/Gift | Hearts                  0.00  Dropshipping
78   684648469279161      08 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684648469379161        Delivered  684648469379161  Product Price Paid by Buyer       standard       0.00    186613209159161                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                                       উপহারের খাম-ফয়েল-প্রিন্টেড সলিড রঙের মানি গিফট খাম (১২ পিস)-বিবাহ, ঈদ এবং বিশেষ অনুষ্ঠানের জন্য প্রিমিয়াম উপহারের খাম [হার্টস  মানি গিফট খাম সোলিড (12 পিস) 4 pkt]                  0.00  Dropshipping
79   685488787692855      08 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685488787792855        Delivered  685488787792855  Product Price Paid by Buyer       standard       0.00    189232194152855                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
85   685500930900299      08 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685500931000299        Delivered  685500931000299  Product Price Paid by Buyer       standard       0.00    188150022150299                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
91   684681413440880      08 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  684681413540880        Delivered  684681413540880  Product Price Paid by Buyer       standard       0.00    189192838150880                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
97   685393318177061      07 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685393318277061        Delivered  685393318277061  Product Price Paid by Buyer       standard       0.00    189188257157061                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
103  684616423260806      07 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684616423360806        Delivered  684616423360806  Product Price Paid by Buyer       standard       0.00    186565825150806                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
110  684612234981556      06 Mar 2026    365.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531252237_BD-2549354280       13  Delivered Orders-Delivered Orders  684612235081556        Delivered  684612235081556  Product Price Paid by Buyer       standard       0.00    189116138151556                                    20250527/3  02 Mar 2026 - 08 Mar 2026                                                                                                                                   Educational Bangladesh Map Puzzle – Learning Toy for Kids, Students & Schools [Hearts My Country Puzzle]                  0.00  Dropshipping
115  685391751003924      06 Mar 2026    345.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531252237_BD-2549354280       13  Delivered Orders-Delivered Orders  685391751103924        Delivered  685391751103924  Product Price Paid by Buyer       standard       0.00    189116014153924                                    20250527/3  02 Mar 2026 - 08 Mar 2026                                                                                                                                                                 শিক্ষামূলক বাংলাদেশ ম্যাপ পাজল-বাচ্চাদের, শিশু এবং স্কুলের জন্য খেলনা শেখা                  0.00  Dropshipping
121  684495229392293      06 Mar 2026    180.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684495229492293        Delivered  684495229492293  Product Price Paid by Buyer       standard       0.00    186517959152293                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
128  685428106728759      06 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685428106828759        Delivered  685428106828759  Product Price Paid by Buyer       standard       0.00    188042493158759                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
134  685441948474855      06 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685441948574855        Delivered  685441948574855  Product Price Paid by Buyer       standard       0.00    189415910154855                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
140  685323556772256      06 Mar 2026    150.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685323556872256        Delivered  685323556872256  Product Price Paid by Buyer       standard       0.00    186501172152256                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
146  684567856564045      05 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  684567856664045        Delivered  684567856664045  Product Price Paid by Buyer       standard       0.00    189028919154045                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
167  685367187339602      05 Mar 2026    210.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685367187439602        Delivered  685367187439602  Product Price Paid by Buyer       standard       0.00    189367898159602                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
168  684554824539602      05 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684554824739602        Delivered  684554824739602  Product Price Paid by Buyer       standard       0.00    189016891159602                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
169  684554824539602      05 Mar 2026    240.00        paid            BD-DEX                     No  EFT_SCB_Mar'26  531423209_BD-2549484889       13  Delivered Orders-Delivered Orders  684554824639602        Delivered  684554824639602  Product Price Paid by Buyer       standard       0.00    189016890159602                                    20250602/1  02 Mar 2026 - 08 Mar 2026                                                        Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]                  0.00  Dropshipping
170  684493425043613      05 Mar 2026    150.00        paid            BD-BPO                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  684493425143613        Delivered  684493425143613  Product Price Paid by Buyer       standard       0.00    189016886153613                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
178  685346350183145      05 Mar 2026    150.00        paid            BD-BPO                     No  EFT_SCB_Mar'26  531411046_BD-2549486307       13  Delivered Orders-Delivered Orders  685346350283145        Delivered  685346350283145  Product Price Paid by Buyer       standard       0.00    186461618153145                                    20250601/1  02 Mar 2026 - 08 Mar 2026                                                                                                            Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]                  0.00  Dropshipping
183  685379548272706      05 Mar 2026    490.00        paid   BD-Paperfly-API                     No  EFT_SCB_Mar'26  540810126_BD-2558921217       13  Delivered Orders-Delivered Orders  685379548372706        Delivered  685379548372706  Product Price Paid by Buyer       standard       0.00    189032223152706            20250727/6-Roll/Bangla 200 Page-A4  02 Mar 2026 - 08 Mar 2026                                                                       Hearts Floral Spiral Khata – 200 Pages – (3 Pcs of Set) – Stylish Medium Notebook for School, College, Office – Beautiful Floral Cover Design – Smooth Writing Paper                  0.00  Dropshipping

In [234]:
df[
    (df["order_no"] == "683734719067225") 
    # & (df["amount"] == 190.00)
]

            order_no transaction_date    amount paid_status WHT_included_in_amount  payment_ref_id fee_type                           transaction_type        reference                                fee_name WHT_amount transaction_number                  statement comment VAT_in_amount shipping_provider               lazada_sku     orderItem_no orderItem_status shipping_speed      seller_sku                                                                                                                                    details shipment_type
168  683734719067225      06 Jan 2026    -24.15        paid                     No  EFT_SCB_Jan'26      114  Services-Logistics & Fulfillment Services  683734719167225                            Handling Fee       0.00    683734719167225  05 Jan 2026 - 11 Jan 2026                  3.15               NaN                      NaN              NaN              NaN            NaN             NaN                                                                                                                                        NaN           NaN
169  683734719067225      06 Jan 2026   -196.56        paid                     No  EFT_SCB_Jan'26       16          Delivered Orders-Transaction Fees  683734719167225                          Commission Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                 25.64            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping
170  683734719067225      06 Jan 2026    -70.00        paid                     No  EFT_SCB_Jan'26       28          Delivered Orders-Transaction Fees  683734719167225                            Shipping Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  9.13            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping
171  683734719067225      06 Jan 2026    -33.66        paid                     No  EFT_SCB_Jan'26        3          Delivered Orders-Transaction Fees  683734719167225                             Payment Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  4.39            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping
172  683734719067225      06 Jan 2026     70.00        paid                     No  EFT_SCB_Jan'26        8          Delivered Orders-Delivered Orders  683734719167225              Shipping Fee Paid by Buyer       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.00            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping
173  683734719067225      06 Jan 2026  1,088.00        paid                     No  EFT_SCB_Jan'26       13          Delivered Orders-Delivered Orders  683734719167225             Product Price Paid by Buyer       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.00            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping
174  683734719067225      06 Jan 2026     -1.05        paid                     No  EFT_SCB_Jan'26     5028          Delivered Orders-Transaction Fees  683734719167225  Daraz Coins Discount Participation Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.05            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping

In [90]:
df.all()

order_no                   True
transaction_date           True
amount                     True
paid_status                True
WHT_included_in_amount     True
payment_ref_id             True
fee_type                   True
transaction_type           True
reference                  True
fee_name                   True
WHT_amount                 True
transaction_number         True
statement                  True
comment                   False
VAT_in_amount              True
shipping_provider          True
lazada_sku                 True
orderItem_no               True
orderItem_status           True
shipping_speed             True
seller_sku                 True
details                    True
shipment_type              True
dtype: bool

In [ ]:
df["statement"].head(100)

In [294]:
request = iop.IopRequest('/order/get', 'GET')

request.add_api_param('access_token', access_token)
request.add_api_param('order_id', "683075420532380")

response = client.execute(request, access_token)

order_data_json = response.body
order = json.loads(order_data_json)["data"]

order

{'warehouse_code': 'dropshipping',
 'voucher': 5.0,
 'order_number': 683075420532380,
 'created_at': '2026-01-09 19:13:23 +0800',
 'voucher_code': '',
 'gift_option': False,
 'shipping_fee_discount_platform': 0.0,
 'customer_last_name': '',
 'updated_at': '2026-01-11 18:45:09 +0800',
 'promised_shipping_times': '',
 'price': '160.00',
 'national_registration_number': '',
 'shipping_fee_original': 70.0,
 'payment_method': 'GNBKASH_TOKEN_EBANK',
 'buyer_note': '',
 'customer_first_name': 'Esrat Jahan  Tonni',
 'shipping_fee_discount_seller': 0.0,
 'shipping_fee': 70.0,
 'branch_number': '',
 'tax_code': '',
 'items_count': 1,
 'delivery_info': '',
 'statuses': ['delivered'],
 'address_billing': {'country': 'Bangladesh',
  'address3': 'Dhaka',
  'address2': '',
  'city': ' Dhaka - North',
  'phone': '88001629807712',
  'address1': 'Roushan Hamlets 5,Building 2,Flat 5B,Opposite of Nayanagar Kacha bazar.Near(UITS).Baridhara J block,Vatara',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': 'Dhaka,  Dhaka - North,  Baridhara',
  'address4': ' Dhaka - North',
  'first_name': 'esrat jahan'},
 'extra_attributes': '',
 'order_id': 683075420532380,
 'gift_message': '',
 'remarks': '',
 'address_shipping': {'country': 'Bangladesh',
  'address3': 'Dhaka',
  'address2': '',
  'city': ' Dhaka - North',
  'phone': '88001629807712',
  'address1': 'Roushan Hamlets 5,Building 2,Flat 5B,Opposite of Nayanagar Kacha bazar.Near(UITS).Baridhara J block,Vatara',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': ' Baridhara',
  'address4': ' Dhaka - North',
  'first_name': 'esrat jahan'}}

In [ ]:
request = iop.IopRequest('/order/get', 'GET')

request.add_api_param('access_token', access_token)
request.add_api_param('order_id', "683657103804574")

response = client.execute(request, access_token)

order_data_json = response.body
order = json.loads(order_data_json)["data"]

order

{'warehouse_code': 'dropshipping',
 'voucher': 195.0,
 'order_number': 683657103804574,
 'created_at': '2026-01-02 21:49:12 +0800',
 'voucher_code': '',
 'gift_option': False,
 'shipping_fee_discount_platform': 0.0,
 'customer_last_name': '',
 'updated_at': '2026-01-06 17:13:50 +0800',
 'promised_shipping_times': '',
 'price': '2176.00',
 'national_registration_number': '',
 'shipping_fee_original': 95.0,
 'payment_method': 'MIXEDCARD',
 'buyer_note': '',
 'customer_first_name': 'Chayet chakma',
 'shipping_fee_discount_seller': 0.0,
 'shipping_fee': 95.0,
 'branch_number': '',
 'tax_code': '',
 'items_count': 2,
 'delivery_info': '',
 'statuses': ['delivered'],
 'address_billing': {'country': 'Bangladesh',
  'address3': 'Chattogram',
  'address2': '',
  'city': 'Rangamati Town',
  'phone': '88001674296567',
  'address1': 'C/o minoti chakma, anupam plaza, banarupa, rangamati- 4500.',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': 'Chattogram, Rangamati Town, Rangamati Sadar',
  'address4': 'Rangamati Town',
  'first_name': 'Priyom Chayet'},
 'extra_attributes': '',
 'order_id': 683657103804574,
 'gift_message': '',
 'remarks': '',
 'address_shipping': {'country': 'Bangladesh',
  'address3': 'Chattogram',
  'address2': '',
  'city': 'Rangamati Town',
  'phone': '8801958188025',
  'address1': 'Daraz Rangamati Head Post Office Collection Point-4500,Rangamati Head Post Office, Rajbari, Rangamati',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': 'Vedvedi',
  'address4': 'Rangamati Town',
  'first_name': 'Priyom Chayet'}}

In [ ]:
import json

order_info = {}

order_ids = df['order_no'].unique()

for order_id in order_ids:
    # order = discount.get_order(order_id)
    request = iop.IopRequest('/order/get', 'GET')

    request.add_api_param('access_token', access_token)
    request.add_api_param('order_id', order_id)

    response = client.execute(request, access_token)

    order_data_json = response.body
    order = json.loads(order_data_json)["data"]
    print(order)
    order_info[
        order_id
    ] = {
        "created_at": order["created_at"],
        "retail_price" : order["price"] if "price" in order else None,
        "voucher" : order["voucher"] if "voucher" in order else 0.0,
    } 

# order_info

In [23]:
# 1️⃣ Clean amount column FIRST
df['amount'] = (
    pd.to_numeric(df['amount'].astype(str).str.replace(',',''), errors='coerce')  # '' or junk → NaN
      .fillna(0)                                  # NaN → 0
)

# define bill amount (only product price rows)
df['Bill Amt'] = np.where(
    df['fee_type'] == "13",
    df['amount'],
    0
)

# define discount base (all others)
df['Discount Base'] = np.where(
    df['fee_type'] != "13",
    df['amount'],
    0
)

In [237]:
df[df['order_no']=='683734719067225']

            order_no transaction_date   amount paid_status WHT_included_in_amount  payment_ref_id fee_type                           transaction_type        reference                                fee_name WHT_amount transaction_number                  statement comment VAT_in_amount shipping_provider               lazada_sku     orderItem_no orderItem_status shipping_speed      seller_sku                                                                                                                                    details shipment_type  Bill Amt  Discount Base
168  683734719067225      06 Jan 2026   -24.15        paid                     No  EFT_SCB_Jan'26      114  Services-Logistics & Fulfillment Services  683734719167225                            Handling Fee       0.00    683734719167225  05 Jan 2026 - 11 Jan 2026                  3.15               NaN                      NaN              NaN              NaN            NaN             NaN                                                                                                                                        NaN           NaN       0.0         -24.15
169  683734719067225      06 Jan 2026  -196.56        paid                     No  EFT_SCB_Jan'26       16          Delivered Orders-Transaction Fees  683734719167225                          Commission Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                 25.64            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping       0.0        -196.56
170  683734719067225      06 Jan 2026   -70.00        paid                     No  EFT_SCB_Jan'26       28          Delivered Orders-Transaction Fees  683734719167225                            Shipping Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  9.13            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping       0.0         -70.00
171  683734719067225      06 Jan 2026   -33.66        paid                     No  EFT_SCB_Jan'26        3          Delivered Orders-Transaction Fees  683734719167225                             Payment Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  4.39            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping       0.0         -33.66
172  683734719067225      06 Jan 2026    70.00        paid                     No  EFT_SCB_Jan'26        8          Delivered Orders-Delivered Orders  683734719167225              Shipping Fee Paid by Buyer       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.00            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping       0.0          70.00
173  683734719067225      06 Jan 2026  1088.00        paid                     No  EFT_SCB_Jan'26       13          Delivered Orders-Delivered Orders  683734719167225             Product Price Paid by Buyer       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.00            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping    1088.0           0.00
174  683734719067225      06 Jan 2026    -1.05        paid                     No  EFT_SCB_Jan'26     5028          Delivered Orders-Transaction Fees  683734719167225  Daraz Coins Discount Participation Fee       0.00    183437131157225  05 Jan 2026 - 11 Jan 2026                  0.05            BD-DEX  529986845_BD-2546835092  683734719167225        Delivered       standard  20250506-Black  প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]  Dropshipping       0.0          -1.05

In [ ]:
# group by order_no
new_df = (
    # df.groupby('transaction_number', as_index=False)
    df.groupby('order_no', as_index=False)
      .agg({
          'order_no': 'first',
          'Bill Amt': 'sum',
          'Discount Base': 'sum',
        #   'transaction_date': 'last'
      })
)

# rename columns
new_df = new_df.rename(columns={
    'order_no': 'Daraz Bill No.',
    'transaction_date': 'Date'
})

# discount amount = total other amounts × (-1)
new_df['Discount Amt'] = new_df['Discount Base'] * -1

# new_df['Discount Amt'] = (
#     pd.to_numeric(
#         new_df["Discount Amt"], errors='coerce'
#     )
#     .fillna(0)
#     .astype(int)
# )
# new_df['Discount Amt'].fillna(0, inplace=True)
# new_df['Discount Amt'].where('') = 0
# new_df['Discount Amt'] = new_df['Discount Amt'].astype(int)

# received amt

# empty columns
new_df['Payment Amt'] = ''
new_df['Remarks'] = ''
new_df['Bill No.'] = ''
new_df['Order Created At'] = new_df["Daraz Bill No."].apply(lambda x : order_info[x]["created_at"])

new_df["Discount Amt"] = new_df.apply(
    lambda x : 
    (
        x["Discount Amt"]
        + float(
            str(
                order_info[x["Daraz Bill No."]]["retail_price"]
                # order_info[x["Daraz Bill No."]]["voucher"]
            ).replace(',','')
        )
        - x["Bill Amt"]
    ) if (
        x["Bill Amt"] != 0.0
    )
    else x["Discount Amt"]
    , 
    axis=1
)

new_df["Discount Amt"] = new_df["Discount Amt"].round(2)

new_df["Bill Amt"] = new_df.apply(
    lambda x : 
    float(order_info[x["Daraz Bill No."]]["retail_price"]) 
    if (
        # (float(x["Bill Amt"]) != float(order_info[x["Daraz Bill No."]]["retail_price"]))
        (float(order_info[x["Daraz Bill No."]]["voucher"]) != 0.0 )
        and (x["Bill Amt"] != 0.0)
    )
    else x["Bill Amt"], 
    axis=1
)

new_df['Received Amt'] = new_df['Bill Amt'] - new_df['Discount Amt']

new_df['Received Amt'] = new_df['Received Amt'].round(2)

print(
    type(new_df["Discount Amt"][0]),
    type(new_df["Bill Amt"][0]),
    type(new_df["Received Amt"][0]),
)
# drop helper column
new_df = new_df.drop(columns=['Discount Base'])

new_df = new_df[[
    'Order Created At', 'Date', 'Payment Amt', 'Bill No.', 
    'Daraz Bill No.', 'Bill Amt', 'Received Amt', 'Discount Amt', 'Remarks'
]]

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>

In [25]:
new_df = new_df.sort_values(
    by=[
        'Order Created At',
        # 'Daraz Bill No.',
        # 'Date', 
    ],
    ascending=[
        False, 
        # False, 
        # False
    ],
).reset_index(drop=True)

In [26]:
new_df

             Order Created At         Date Payment Amt Bill No.   Daraz Bill No.  Bill Amt  Received Amt  Discount Amt Remarks
0   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360       0.0         -6.90          6.90
1   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360     190.0        -45.43        235.43
2   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360       0.0         -6.90          6.90
3   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360     190.0        -45.43        235.43
4   2026-01-09 20:30:19 +0800  11 Jan 2026                       683076270297897     160.0        121.58         38.42
5   2026-01-09 20:30:19 +0800  11 Jan 2026                       683076270297897       0.0         -6.90          6.90
6   2026-01-09 20:21:56 +0800  11 Jan 2026                       683077041067861       0.0         -6.90          6.90
7   2026-01-09 20:21:56 +0800  11 Jan 2026                       683077041067861     160.0        121.58         38.42
8   2026-01-09 19:13:23 +0800  11 Jan 2026                       683075420532380       0.0         -6.90          6.90
9   2026-01-09 19:13:23 +0800  11 Jan 2026                       683075420532380     160.0        118.79         41.21
10  2026-01-09 01:19:22 +0800  11 Jan 2026                       683056460060566       0.0         -6.90          6.90
11  2026-01-09 01:19:22 +0800  11 Jan 2026                       683056460060566     220.0        189.24         30.76
12  2026-01-09 00:59:11 +0800  11 Jan 2026                       683055285536336       0.0         -6.90          6.90
13  2026-01-09 00:59:11 +0800  11 Jan 2026                       683055285536336     160.0        121.58         38.42
14  2026-01-08 23:55:56 +0800  11 Jan 2026                       683054054866959       0.0         -6.90          6.90
15  2026-01-08 23:55:56 +0800  11 Jan 2026                       683054054866959     385.0        287.70         97.30
16  2026-01-08 17:22:51 +0800  09 Jan 2026                       683041857809070       0.0        -24.15         24.15
17  2026-01-08 17:22:51 +0800  09 Jan 2026                       683041857809070    1099.0        840.43        258.57
18  2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207       0.0         -6.90          6.90
19  2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207     380.0        144.57        235.43
20  2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207       0.0         -6.90          6.90
21  2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207     380.0        144.57        235.43
22  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645       0.0         -6.90          6.90
23  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     720.0        173.99        546.01
24  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     720.0        174.74        545.26
25  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     720.0        174.74        545.26
26  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645       0.0         -6.90          6.90
27  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645       0.0         -6.90          6.90
28  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346       0.0         -6.90          6.90
29  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346       0.0         -6.90          6.90
30  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     555.0        134.70        420.30
31  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     555.0        134.70        420.30
32  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     555.0        133.95        421.05
33  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346       0.0         -6.90          6.90
34  2026-01-06 23:36:31 +0800  10 Jan 2026                       683793189508598    1099.0        865.41        233.59
35  2026-01-06 23:36:31 +0800  10 Jan 2026                       683793189508598       0.0        -24.15         24.15
36  2026-01-06 16:01:56 +0800  11 Jan 2026                       682981255345247    1099.0        865.41        233.59
37  2026-01-06 16:01:56 +0800  11 Jan 2026                       682981255345247       0.0        -24.15         24.15
38  2026-01-06 01:44:59 +0800  07 Jan 2026                       682967479941086       0.0         -6.90          6.90
39  2026-01-06 01:44:59 +0800  07 Jan 2026                       682967479941086     240.0        178.94         61.06
40  2026-01-06 00:57:59 +0800  10 Jan 2026                       683764157908439       0.0         -6.90          6.90
41  2026-01-06 00:57:59 +0800  10 Jan 2026                       683764157908439     317.0        252.33         64.67
42  2026-01-05 22:50:35 +0800  07 Jan 2026                       682960812396789       0.0         -6.90          6.90
43  2026-01-05 22:50:35 +0800  07 Jan 2026                       682960812396789     419.0        313.20        105.80
44  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250       0.0         -6.90          6.90
45  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250       0.0         -6.90          6.90
46  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250     250.0        -48.50        298.50
47  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250     250.0        -48.50        298.50
48  2026-01-05 04:43:40 +0800  06 Jan 2026                       683734719067225       0.0        -24.15         24.15
49  2026-01-05 04:43:40 +0800  06 Jan 2026                       683734719067225    1088.0        856.73        231.27
50  2026-01-05 03:18:08 +0800  11 Jan 2026                       682933803784800       0.0        -24.15         24.15
51  2026-01-05 03:18:08 +0800  11 Jan 2026                       682933803784800    1088.0        856.73        231.27
52  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983    1088.0       -231.28       1319.28
53  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983    1088.0       -231.28       1319.28
54  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983       0.0        -24.15         24.15
55  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983       0.0        -24.15         24.15
56  2026-01-04 20:40:21 +0800  06 Jan 2026                       683718368270070     590.0        477.00        113.00
57  2026-01-04 20:40:21 +0800  06 Jan 2026                       683718368270070       0.0        -10.35         10.35
58  2026-01-04 18:58:33 +0800  06 Jan 2026                       683713989368111     240.0        178.94         61.06
59  2026-01-04 18:58:33 +0800  06 Jan 2026                       683713989368111       0.0         -6.90          6.90
60  2026-01-03 21:12:36 +0800  05 Jan 2026                       682888834034742       0.0         -6.90          6.90
61  2026-01-03 21:12:36 +0800  05 Jan 2026                       682888834034742     419.0        304.50        114.50
62  2026-01-03 20:39:20 +0800  05 Jan 2026                       682887441241977       0.0         -6.90          6.90
63  2026-01-03 20:39:20 +0800  05 Jan 2026                       682887441241977     159.0        120.81         38.19
64  2026-01-03 20:36:07 +0800  06 Jan 2026                       682883493968161       0.0        -24.15         24.15
65  2026-01-03 20:36:07 +0800  06 Jan 2026                       682883493968161    1088.0        831.76        256.24
66  2026-01-03 17:23:14 +0800  07 Jan 2026                       682880825703289       0.0         -6.90          6.90
67  2026-01-03 17:23:14 +0800  07 Jan 2026                       682880825703289     159.0        118.04         40.96
68  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053       0.0         -6.90          6.90
69  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053       0.0        -10.35         10.35
70  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053       0.0        -10.35         10.35
71  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053    1780.0        502.19       1277.81
72  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053    1780.0        450.45       1329.55
73  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053    1780.0        361.20       1418.80
74  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574       0.0        -50.03         50.03
75  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574    2176.0        848.05       1327.95
76  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574    2176.0        848.85       1327.15
77  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574       0.0        -24.15         24.15
78  2026-01-01 01:58:30 +0800  11 Jan 2026                       683604323643871       0.0        -34.50         34.50
79  2025-12-31 16:18:38 +0800  05 Jan 2026                       683580389992228    1099.0        865.41        233.59
80  2025-12-31 16:18:38 +0800  05 Jan 2026                       683580389992228       0.0        -47.15         47.15
81  2025-12-31 14:13:58 +0800  11 Jan 2026                       682781438686903       0.0        -23.00         23.00
82  2025-12-30 16:56:25 +0800  11 Jan 2026                       683557150877189       0.0        -59.80         59.80
83  2025-12-29 16:39:13 +0800  11 Jan 2026                       682727219314052       0.0        -23.00         23.00

In [343]:
print(
    type(new_df["Bill Amt"][0]),
    type(new_df["Discount Amt"][0]),
    type(new_df["Received Amt"][0]),
)

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>

In [344]:
new_df[[
    'Bill Amt',
    'Received Amt', 
    'Discount Amt', 
]].sum()

Bill Amt        20115.00
Received Amt    14853.11
Discount Amt     5261.89
dtype: float64

## call module

In [ ]:
new_df = discount.fetch_and_process_data(access_token)
# new_df

In [ ]:
trans =discount.get_trans(
    access_token,
    start_date="2026-01-05",
    end_date="2026-01-11",
    # order_id="683008658108645"
)

In [ ]:
trans

In [15]:
order = discount.get_order("683008658108645")

In [2]:
from discount import discount
order = discount.get_order_items("684403864843903")
order

[{'tax_amount': 0.0,
  'pick_up_store_info': {},
  'reason': '',
  'sla_time_stamp': '',
  'purchase_order_id': '',
  'voucher_seller': 5.0,
  'payment_time': 1772432118414,
  'voucher_code_seller': '',
  'voucher_code': '',
  'package_id': 'FP044711155054054',
  'buyer_id': 700049043903,
  'variation': 'Color family:Multicolor, Paper Type:Not Specified',
  'biz_group': 70100,
  'product_id': '531411046',
  'voucher_code_platform': '',
  'purchase_order_number': '',
  'sku': '20250601/1',
  'gift_wrapping': '',
  'order_type': 'Normal',
  'invoice_number': '20250228/03',
  'cancel_return_initiator': 'null-null',
  'shop_sku': '531411046_BD-2549486307',
  'is_reroute': 0,
  'stage_pay_status': '',
  'sku_id': '2549486307',
  'tracking_code_pre': '',
  'order_item_id': 684403864943903,
  'shop_id': 'Hearts Bangladesh ',
  'order_flag': 'NORMAL',
  'is_fbl': 0,
  'name': 'Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]',
  'delivery_option_sof': 0,
  'order_id': 684403864843903,
  'fulfillment_sla': 'null_null_null',
  'status': 'delivered',
  'paid_price': 145.0,
  'product_main_image': 'https://static-01.daraz.com.bd/p/3610dab890f3c9e169c51197d388427f.png',
  'voucher_platform': 0,
  'product_detail_url': 'https://www.daraz.com.bd/products/i531411046-s2549486307.html?urlFlag=true&mp=1',
  'warehouse_code': 'dropshipping',
  'promised_shipping_time': '',
  'shipping_type': 'Dropshipping',
  'created_at': '2026-02-27 04:01:47 +0800',
  'supply_price': 0,
  'mp3_order': False,
  'voucher_seller_lpi': 5.0,
  'shipping_fee_discount_platform': 0,
  'personalization': '',
  'wallet_credits': 0,
  'updated_at': '2026-03-02 14:15:19 +0800',
  'currency': 'BDT',
  'shipping_provider_type': 'standard',
  'voucher_platform_lpi': 0.0,
  'shipping_fee_original': 70.0,
  'is_digital': 0,
  'item_price': 150.0,
  'shipping_service_cost': 0,
  'tracking_code': 'DEX-BDN-0110688726',
  'shipping_fee_discount_seller': 0,
  'reason_detail': '',
  'shipping_amount': 70.0,
  'return_status': '',
  'semi_managed': False,
  'shipment_provider': 'Drop-off: BD-DEX, Delivery: BD-DEX',
  'priority_fulfillment_tag': '',
  'voucher_amount': 5.0,
  'supply_price_currency': '',
  'extra_attributes': '',
  'digital_delivery_info': 'tasfiabari3@gmail.com'}]

In [ ]:
order

[{'tax_amount': 0.0,
  'pick_up_store_info': {},
  'reason': '',
  'sla_time_stamp': '',
  'purchase_order_id': '',
  'voucher_seller': 7.0,
  'payment_time': 1767857958132,
  'voucher_code_seller': '',
  'voucher_code': '',
  'package_id': 'FP038911153084840',
  'buyer_id': 700019808645,
  'variation': 'Color family:Black, Paper Type:A5',
  'biz_group': 70100,
  'product_id': '530254219',
  'voucher_code_platform': '',
  'purchase_order_number': '',
  'sku': '20250508-Black-A5',
  'gift_wrapping': '',
  'order_type': 'Normal',
  'invoice_number': '20260107/04',
  'cancel_return_initiator': 'null-null',
  'shop_sku': '530254219_BD-2546970371',
  'is_reroute': 0,
  'stage_pay_status': '',
  'sku_id': '2546970371',
  'tracking_code_pre': '',
  'order_item_id': 683008658208645,
  'shop_id': 'Hearts Bangladesh ',
  'order_flag': 'NORMAL',
  'is_fbl': 0,
  'name': 'Premium PU Leather Daily Notebook / Jornal [Hearts- EB\xa0Notebook',
  'delivery_option_sof': 0,
  'order_id': 683008658108645,
  'fulfillment_sla': 'null_null_null',
  'status': 'delivered',
  'paid_price': 233.0,
  'product_main_image': 'https://static-01.daraz.com.bd/p/7ed737d5821b940b73879a57e836d636.jpg',
  'voucher_platform': 0,
  'product_detail_url': 'https://www.daraz.com.bd/products/i530254219-s2546970371.html?urlFlag=true&mp=1',
  'warehouse_code': 'dropshipping',
  'promised_shipping_time': '',
  'shipping_type': 'Dropshipping',
  'created_at': '2026-01-07 14:21:39 +0800',
  'supply_price': 0,
  'mp3_order': False,
  'voucher_seller_lpi': 7.0,
  'shipping_fee_discount_platform': 0,
  'personalization': '',
  'wallet_credits': 0,
  'updated_at': '2026-01-08 15:39:29 +0800',
  'currency': 'BDT',
  'shipping_provider_type': 'standard',
  'voucher_platform_lpi': 0.0,
  'shipping_fee_original': 23.0,
  'is_digital': 0,
  'item_price': 240.0,
  'shipping_service_cost': 0,
  'tracking_code': 'DEX-BDN-0109507781',
  'shipping_fee_discount_seller': 0,
  'reason_detail': '',
  'shipping_amount': 23.0,
  'return_status': '',
  'semi_managed': False,
  'shipment_provider': 'Drop-off: BD-DEX, Delivery: BD-DEX',
  'priority_fulfillment_tag': '',
  'voucher_amount': 7.0,
  'supply_price_currency': '',
  'extra_attributes': '',
  'digital_delivery_info': 'mkdewry777@gmail.com'},
 {'tax_amount': 0.0,
  'pick_up_store_info': {},
  'reason': '',
  'sla_time_stamp': '',
  'purchase_order_id': '',
  'voucher_seller': 8.0,
  'payment_time': 1767857958132,
  'voucher_code_seller': '',
  'voucher_code': '',
  'package_id': 'FP038911153084840',
  'buyer_id': 700019808645,
  'variation': 'Color family:Black, Paper Type:A5',
  'biz_group': 70100,
  'product_id': '530254219',
  'voucher_code_platform': '',
  'purchase_order_number': '',
  'sku': '20250508-Black-A5',
  'gift_wrapping': '',
  'order_type': 'Normal',
  'invoice_number': '20260107/04',
  'cancel_return_initiator': 'null-null',
  'shop_sku': '530254219_BD-2546970371',
  'is_reroute': 0,
  'stage_pay_status': '',
  'sku_id': '2546970371',
  'tracking_code_pre': '',
  'order_item_id': 683008658308645,
  'shop_id': 'Hearts Bangladesh ',
  'order_flag': 'NORMAL',
  'is_fbl': 0,
  'name': 'Premium PU Leather Daily Notebook / Jornal [Hearts- EB\xa0Notebook',
  'delivery_option_sof': 0,
  'order_id': 683008658108645,
  'fulfillment_sla': 'null_null_null',
  'status': 'delivered',
  'paid_price': 232.0,
  'product_main_image': 'https://static-01.daraz.com.bd/p/7ed737d5821b940b73879a57e836d636.jpg',
  'voucher_platform': 0,
  'product_detail_url': 'https://www.daraz.com.bd/products/i530254219-s2546970371.html?urlFlag=true&mp=1',
  'warehouse_code': 'dropshipping',
  'promised_shipping_time': '',
  'shipping_type': 'Dropshipping',
  'created_at': '2026-01-07 14:21:39 +0800',
  'supply_price': 0,
  'mp3_order': False,
  'voucher_seller_lpi': 8.0,
  'shipping_fee_discount_platform': 0,
  'personalization': '',
  'wallet_credits': 0,
  'updated_at': '2026-01-08 15:39:29 +0800',
  'currency': 'BDT',
  'shipping_provider_type': 'standard',
  'voucher_platform_lpi': 0.0,
  'shipping_fee_original': 23.0,
  'is_digital': 0,
  'item_price': 240.0,
  'shipping_service_cost': 0,
  'tracking_code': 'DEX-BDN-0109507781',
  'shipping_fee_discount_seller': 0,
  'reason_detail': '',
  'shipping_amount': 23.0,
  'return_status': '',
  'semi_managed': False,
  'shipment_provider': 'Drop-off: BD-DEX, Delivery: BD-DEX',
  'priority_fulfillment_tag': '',
  'voucher_amount': 8.0,
  'supply_price_currency': '',
  'extra_attributes': '',
  'digital_delivery_info': 'mkdewry777@gmail.com'},
 {'tax_amount': 0.0,
  'pick_up_store_info': {},
  'reason': '',
  'sla_time_stamp': '',
  'purchase_order_id': '',
  'voucher_seller': 7.0,
  'payment_time': 1767857958132,
  'voucher_code_seller': '',
  'voucher_code': '',
  'package_id': 'FP038911153084840',
  'buyer_id': 700019808645,
  'variation': 'Color family:Black, Paper Type:A5',
  'biz_group': 70100,
  'product_id': '530254219',
  'voucher_code_platform': '',
  'purchase_order_number': '',
  'sku': '20250508-Black-A5',
  'gift_wrapping': '',
  'order_type': 'Normal',
  'invoice_number': '20260107/04',
  'cancel_return_initiator': 'null-null',
  'shop_sku': '530254219_BD-2546970371',
  'is_reroute': 0,
  'stage_pay_status': '',
  'sku_id': '2546970371',
  'tracking_code_pre': '',
  'order_item_id': 683008658408645,
  'shop_id': 'Hearts Bangladesh ',
  'order_flag': 'NORMAL',
  'is_fbl': 0,
  'name': 'Premium PU Leather Daily Notebook / Jornal [Hearts- EB\xa0Notebook',
  'delivery_option_sof': 0,
  'order_id': 683008658108645,
  'fulfillment_sla': 'null_null_null',
  'status': 'delivered',
  'paid_price': 233.0,
  'product_main_image': 'https://static-01.daraz.com.bd/p/7ed737d5821b940b73879a57e836d636.jpg',
  'voucher_platform': 0,
  'product_detail_url': 'https://www.daraz.com.bd/products/i530254219-s2546970371.html?urlFlag=true&mp=1',
  'warehouse_code': 'dropshipping',
  'promised_shipping_time': '',
  'shipping_type': 'Dropshipping',
  'created_at': '2026-01-07 14:21:39 +0800',
  'supply_price': 0,
  'mp3_order': False,
  'voucher_seller_lpi': 7.0,
  'shipping_fee_discount_platform': 0,
  'personalization': '',
  'wallet_credits': 0,
  'updated_at': '2026-01-08 15:39:29 +0800',
  'currency': 'BDT',
  'shipping_provider_type': 'standard',
  'voucher_platform_lpi': 0.0,
  'shipping_fee_original': 24.0,
  'is_digital': 0,
  'item_price': 240.0,
  'shipping_service_cost': 0,
  'tracking_code': 'DEX-BDN-0109507781',
  'shipping_fee_discount_seller': 0,
  'reason_detail': '',
  'shipping_amount': 24.0,
  'return_status': '',
  'semi_managed': False,
  'shipment_provider': 'Drop-off: BD-DEX, Delivery: BD-DEX',
  'priority_fulfillment_tag': '',
  'voucher_amount': 7.0,
  'supply_price_currency': '',
  'extra_attributes': '',
  'digital_delivery_info': 'mkdewry777@gmail.com'}]

In [20]:
amounts = [
    float(tran["amount"])
    for tran in trans
    if tran["fee_type"] == "13"
]

retailSum = sum(
    amounts
)

retailSum, amounts

(698.0, [233.0, 232.0, 233.0])

In [16]:
order

{'warehouse_code': 'dropshipping',
 'voucher': 22.0,
 'order_number': 683008658108645,
 'created_at': '2026-01-07 14:21:39 +0800',
 'voucher_code': '',
 'gift_option': False,
 'shipping_fee_discount_platform': 0.0,
 'customer_last_name': '',
 'updated_at': '2026-01-08 15:39:29 +0800',
 'promised_shipping_times': '',
 'price': '720.00',
 'national_registration_number': '',
 'shipping_fee_original': 70.0,
 'payment_method': 'COD',
 'buyer_note': '',
 'customer_first_name': 'Maverick Michael',
 'shipping_fee_discount_seller': 0.0,
 'shipping_fee': 70.0,
 'branch_number': '',
 'tax_code': '',
 'items_count': 3,
 'delivery_info': '',
 'statuses': ['delivered'],
 'address_billing': {'country': 'Bangladesh',
  'address3': 'Dhaka',
  'address2': '',
  'city': ' Savar',
  'phone': '8801717790592',
  'address1': 'CCDB HOPE FOUNDATION Baroipara, Savar, Dhaka, Bangladesh.',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': 'Dhaka,  Savar,  Savar Baroipara',
  'address4': ' Savar',
  'first_name': 'Michael Dewry'},
 'extra_attributes': '',
 'order_id': 683008658108645,
 'gift_message': '',
 'remarks': '',
 'address_shipping': {'country': 'Bangladesh',
  'address3': 'Dhaka',
  'address2': '',
  'city': ' Savar',
  'phone': '8801717790592',
  'address1': 'CCDB HOPE FOUNDATION Baroipara, Savar, Dhaka, Bangladesh.',
  'post_code': '',
  'phone2': '',
  'last_name': '',
  'address5': ' Savar Baroipara',
  'address4': ' Savar',
  'first_name': 'Michael Dewry'}}

In [25]:
import pandas as pd
import numpy as np

pd.set_option('display.max_rows', None)
pd.set_option('display.max_columns', None)
pd.set_option('display.max_colwidth', None)
pd.set_option('display.width', None)
pd.set_option('display.expand_frame_repr', False)
# df = pd.DataFrame(data)
df = pd.DataFrame(trans)
# df.head(100)

In [25]:
df.all().keys()

Index(['order_no', 'transaction_date', 'amount', 'paid_status',
       'WHT_included_in_amount', 'payment_ref_id', 'fee_type',
       'transaction_type', 'reference', 'fee_name', 'WHT_amount',
       'transaction_number', 'statement', 'comment', 'VAT_in_amount',
       'shipping_provider', 'lazada_sku', 'orderItem_no', 'orderItem_status',
       'shipping_speed', 'seller_sku', 'details', 'shipment_type', 'Bill Amt',
       'Discount Base'],
      dtype='object')

In [27]:
for col in df.all().keys():
    print(
        col, 
        len(df[col].unique()), 
        df[col].unique(), 
    )

order_no 33 ['683055285536336' '683056460060566' '682933803784800' '683075420532380'
 '682727219314052' '683604323643871' '683580389992228' '683557150877189'
 '683657103804574' '682781438686903' '683893397749360' '683054054866959'
 '683077041067861' '683076270297897' '682981255345247' '683793189508598'
 '683764157908439' '683830795720207' '683041857809070' '682994240042346'
 '683008658108645' '682960812396789' '682967479941086' '682880825703289'
 '683734719067225' '683718368270070' '683659527372053' '682883493968161'
 '683713989368111' '683732746710983' '683747925422250' '682887441241977'
 '682888834034742']
transaction_date 7 ['11 Jan 2026' '10 Jan 2026' '09 Jan 2026' '08 Jan 2026' '07 Jan 2026'
 '06 Jan 2026' '05 Jan 2026']
amount 107 [-6.9000e+00 -3.2420e+01 -7.0000e+01 -4.9500e+00  7.0000e+01  1.6000e+02
 -1.0500e+00 -2.2900e+01 -1.4300e+02 -6.8100e+00  1.4300e+02  2.2000e+02
 -2.4150e+01 -1.9656e+02 -4.4000e+01 -3.3660e+01  4.4000e+01  1.0880e+03
 -3.1410e+01 -4.8000e+00  1.5500e+02 -2.3000e+01 -3.4500e+01 -5.9800e+01
 -2.5880e+01 -3.8500e+01 -2.2000e+01 -5.8800e+00  2.2000e+01  2.3000e+01
  1.9000e+02 -8.4340e+01 -1.1910e+01  3.8500e+02 -1.9855e+02 -3.3990e+01
  1.0990e+03 -5.3810e+01 -9.8100e+00  3.1700e+02 -6.6000e+01  6.6000e+01
 -1.9259e+02 -3.2980e+01  1.0660e+03 -3.9430e+01 -2.4000e+01 -5.5700e+00
  2.4000e+01 -3.9650e+01 -5.6000e+00  1.8000e+02  1.8100e+02 -5.1050e+01
 -7.2100e+00 -5.0830e+01 -7.1800e+00  2.3300e+02  2.3200e+02 -9.1790e+01
 -1.2960e+01  4.1900e+02 -5.2580e+01 -7.4300e+00  2.4000e+02 -3.1200e+01
 -4.7600e+00  1.5400e+02 -1.0350e+01 -9.3700e+01 -1.8250e+01  5.9000e+02
 -1.4700e+02 -2.0760e+01 -1.3188e+02 -1.8620e+01 -1.0581e+02 -1.4940e+01
 -1.9475e+02 -4.7000e+01 -3.3350e+01  4.7000e+01 -1.9458e+02 -4.8000e+01
 -3.3320e+01  4.8000e+01 -1.9060e+02 -3.2640e+01  6.7100e+02  6.0200e+02
  4.8300e+02  1.0780e+03  1.0770e+03  1.0550e+03 -8.1010e+01  8.1000e+01
 -3.9710e+01 -5.5000e+01 -7.7400e+00  5.5000e+01  2.5000e+02 -3.2220e+01
 -4.9200e+00  1.5900e+02 -8.8940e+01 -1.2560e+01  4.0600e+02]
paid_status 1 ['paid']
WHT_included_in_amount 1 ['No']
payment_ref_id 1 ["EFT_SCB_Jan'26"]
fee_type 8 ['114' '16' '28' '3' '8' '13' '5028' '172']
transaction_type 4 ['Services-Logistics & Fulfillment Services'
 'Delivered Orders-Transaction Fees' 'Delivered Orders-Delivered Orders'
 'Delivered Orders-Delivered Orders Marked Delivery Failed']
reference 44 ['683055285636336' '683056460160566' '682933803884800' '683075420632380'
 '682727219414052' '683604323743871' '683580390092228' '683557151377189'
 '683657103904574' '682781438786903' '683893397949360' '683893397849360'
 '683054054966959' '683077041167861' '683076270397897' '682981255445247'
 '683793189608598' '683764158008439' '683830795820207' '683830795920207'
 '683041857909070' '682994240242346' '682994240342346' '682994240142346'
 '683008658308645' '683008658208645' '683008658408645' '682960812496789'
 '682967480041086' '682880825803289' '683734719167225' '683718368370070'
 '683659527672053' '683657104004574' '683659527472053' '683659527572053'
 '682883494068161' '683713989468111' '683732746810983' '683732746910983'
 '683747927422250' '683747927322250' '682887441341977' '682888834134742']
fee_name 7 ['Handling Fee' 'Commission Fee' 'Shipping Fee' 'Payment Fee'
 'Shipping Fee Paid by Buyer' 'Product Price Paid by Buyer'
 'Daraz Coins Discount Participation Fee']
WHT_amount 1 ['0.00']
transaction_number 84 ['683055285636336' '186108394156336' '683056460160566' '183745588150566'
 '682933803884800' '185206887154800' '683075420632380' '186096386152380'
 '682727219414052' '683604323743871' '683580390092228' '683557151377189'
 '683657103904574' '682781438786903' '683893397949360' '683893397849360'
 '183737603159360' '183737602159360' '683054054966959' '185186471156959'
 '683077041167861' '186519379157861' '683076270397897' '186072164157897'
 '682981255445247' '185166483155247' '683793189608598' '186471972158598'
 '683764158008439' '183593091158439' '683830795820207' '683830795920207'
 '183585761150207' '183585760150207' '683041857909070' '186411719159070'
 '682994240242346' '682994240342346' '682994240142346' '186407209152346'
 '186407208152346' '186407207152346' '683008658308645' '683008658208645'
 '683008658408645' '183509166158645' '183509165158645' '183509164158645'
 '682960812496789' '185888055156789' '682967480041086' '186267243151086'
 '682880825803289' '185856624153289' '683734719167225' '183437131157225'
 '683718368370070' '184914965150070' '683659527672053' '683657104004574'
 '683659527472053' '683659527572053' '682883494068161' '186207308152053'
 '186207307152053' '186207306152053' '185820296154574' '185820295154574'
 '185816698158161' '683713989468111' '185812528158111' '683732746810983'
 '683732746910983' '185788476150983' '185788472150983' '683747927422250'
 '683747927322250' '184874161152250' '184874160152250' '186155512152228'
 '682887441341977' '186123224151977' '682888834134742' '184798255154742']
statement 1 ['05 Jan 2026 - 11 Jan 2026']
comment 7 ['' 'Clawback_SKU: 529986845_BD-2546835094_Tracking# DEX-BDN-0109277716'
 'Clawback_SKU: 529986845_BD-2546835094_Tracking# DEX-BDN-0109332995'
 'Clawback_SKU: 529986845_BD-2546835094_Tracking# PAT-BD-0001111353'
 'Clawback_SKU: 529986845_BD-2546835094_Tracking# DEX-BDN-0109302285'
 'Clawback_SKU: 529986845_BD-2546835094_Tracking# BD-BPO-0126517065'
 'Clawback_SKU: 529986845_BD-2546835093_Tracking# PFL-BD0022491045']
VAT_in_amount 68 ['0.90' '4.23' '9.13' '0.65' '0.00' '0.05' '2.99' '18.65' '0.89' '3.15'
 '25.64' '5.74' '4.39' '4.10' '0.63' '3.00' '4.50' '7.80' '3.38' '5.02'
 '2.87' '0.77' '11.00' '1.55' '25.90' '4.43' '7.02' '1.28' '8.61' '25.12'
 '4.30' '5.14' '3.13' '0.73' '5.17' '6.66' '0.94' '6.63' '11.97' '1.69'
 '6.86' '0.97' '4.07' '0.62' '1.35' '12.22' '2.38' '19.17' '2.71' '17.20'
 '2.43' '13.80' '1.95' '25.40' '6.13' '4.35' '25.38' '6.26' '24.86' '4.26'
 '10.57' '5.18' '7.17' '1.01' '4.20' '0.64' '11.60' '1.64']
shipping_provider 5 [nan 'BD-DEX' 'BD-Pathao-API' 'BD-BPO' 'BD-Paperfly-API']
lazada_sku 22 [nan '531411046_BD-2549486307' '531176163_BD-2549240698'
 '529986845_BD-2546835093' '529986845_BD-2546835094'
 '531423209_BD-2549484889' '538522854_BD-2554329035'
 '534781993_BD-2551906335' '529986845_BD-2589405868'
 '530164066_BD-2609049308' '530164066_BD-2609049306'
 '530164066_BD-2609049307' '530254219_BD-2546970371'
 '531288268_BD-2549374488' '530254219_BD-2546970372'
 '529986845_BD-2546835092' '545939119_BD-2581116864'
 '540802174_BD-2558909663' '540785852_BD-2558912598'
 '540810126_BD-2558921217' '545932121_BD-2568137668'
 '545932121_BD-2568137676']
orderItem_no 45 [nan '683055285636336' '683056460160566' '682933803884800'
 '683075420632380' '682727219414052' '683604323743871' '683580390092228'
 '683557151377189' '683657103904574' '682781438786903' '683893397949360'
 '683893397849360' '683054054966959' '683077041167861' '683076270397897'
 '682981255445247' '683793189608598' '683764158008439' '683830795920207'
 '683830795820207' '683041857909070' '682994240342346' '682994240242346'
 '682994240142346' '683008658408645' '683008658308645' '683008658208645'
 '682960812496789' '682967480041086' '682880825803289' '683734719167225'
 '683718368370070' '683659527672053' '683659527572053' '683659527472053'
 '683657104004574' '682883494068161' '683713989468111' '683732746910983'
 '683732746810983' '683747927422250' '683747927322250' '682887441341977'
 '682888834134742']
orderItem_status 2 [nan 'Delivered']
shipping_speed 2 [nan 'standard']
seller_sku 22 [nan '20250601/1' '20250525/1-Golden Mount Art' '20250506-Brown'
 '20250506-Chili Red' '20250602/1' '20250713/1' '20250626/2'
 '220250927/04' '530164066-Green Floral - Metal-Not Specified'
 '530164066-Green Floral -Velvet-Not Specified'
 '530164066-Blue Floral - Velvet-Not Specified' '20250508-Black-A5'
 '20250528/01-Coffee-A5' '20250508-Coffee-A5' '20250506-Black'
 '20250908/4' '20250727/4-Roll/bangla 300 page-A4'
 '20270727/7-Roll/Bangla 120 Page' '20250727/6-Roll/Bangla 200 Page-A4'
 '20250827/01-Item-02-Other' '20250827/01-Item-10-Other']
details 16 [nan
 'Premium Gift Envelopes (18 Pcs) – Elegant Money & Letter for Salami, Events & Special Occasions [ Hearts Gift Envelops-18 Pcs ]'
 "Hearts Travelers Drawing Book / Sketchbook – Big Drawing Pad (7.2'' x 7.2'') for Artists & Kids | Portable Sketch Pad for On-the-Go Drawing [ Hearts Travelers Drawing Book Big ]"
 'Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents\xa0Folder]'
 'Gift Envelop-Foil-Printed Solid Color Money Gift Envelopes (12 Pcs) – Premium Gift Envelopes for Weddings, Eid & Special Occasions [ Hearts Money Gift Envelop Solid (12 Pcs)4 Pkt]'
 'Premium PU Leather Spiral Notebook – Loop Lock Journal with Printed Design for Office & Gift Use [Hearts Executive DX Notebook]'
 'PU Leather Telephone Index Book – 180 Pages, 100 GSM Offset Paper [ Hearts Office Telephone Index]'
 'Spiral Crown Notebook – Durable Wire-Bound Notebook / Journal for Daily Writing & Study Use [Hearts Crown Notebook]'
 'Premium PU Leather Daily Notebook / Jornal [Hearts- EB\xa0Notebook'
 'Hearts Bangladesh PU Leather Premium Notebook – 192 Pages, Book-Bound Executive Journal (9.75 x 7 Inch) [Hearts Oriental Notebook]'
 'প্রিমিয়াম পিউ লেদার ডকুমেন্ট ফোল্ডার/আইনী পেপার হোল্ডার/অফিস, বিজনেস এবং কোর্ট ব্যবহারের জন্য ফাইল অর্গানাইজার [হার্টস ডকুমেন্ট ফোল্ডার]'
 'Hearts Executive Diary 2026 – Elegant PU Leather  Diary, Notebook, Office Planner, Professional Business Diary for Notes, Meetings, Scheduling & Daily Organization [Executive Diary-2026]'
 'Hearts Floral Spiral Khata – 300 Pages –(3 Pcs) – Premium Quality Notebook for School, College, Office Use – Stylish Cover Design'
 'Floral Spiral Khata/Notebook/Pads – 120 Pages(6 pcs of set)  – Regular Size Notebook – Stylish Floral Cover – School, College, Office Use – Durable Spiral Binding'
 'Hearts Floral Spiral Khata – 200 Pages – (3 Pcs of Set) – Stylish Medium Notebook for School, College, Office – Beautiful Floral Cover Design – Smooth Writing Paper'
 'Hearts General Diary 2026 – Premium Quality Daily Planner with Smooth Writing Paper, Durable Binding, Elegant Professional Design, Perfect for Office, Business, Study, Journaling, Personal Notes, and Everyday Use {Hearts General Diary-2026]']
shipment_type 2 [nan 'Dropshipping']
Bill Amt 27 [   0.  160.  220. 1088.  155.  190.  385. 1099.  317. 1066.  180.  181.
  233.  232.  419.  240.  154.  590.  671.  602.  483. 1078. 1077. 1055.
  250.  159.  406.]
Discount Base 82 [  -6.9   -32.42  -70.     -4.95   70.      0.     -1.05  -22.9  -143.
   -6.81  143.    -24.15 -196.56  -44.    -33.66   44.    -31.41   -4.8
  -23.    -34.5   -59.8   -25.88  -38.5   -22.     -5.88   22.     23.
  -84.34  -11.91 -198.55  -33.99  -53.81   -9.81  -66.     66.   -192.59
  -32.98  -39.43  -24.     -5.57   24.    -39.65   -5.6   -51.05   -7.21
  -50.83   -7.18  -91.79  -12.96  -52.58   -7.43  -31.2    -4.76  -10.35
  -93.7   -18.25 -147.    -20.76 -131.88  -18.62 -105.81  -14.94 -194.75
  -47.    -33.35   47.   -194.58  -48.    -33.32   48.   -190.6   -32.64
  -81.01   81.    -39.71  -55.     -7.74   55.    -32.22   -4.92  -88.94
  -12.56]

In [18]:
refs = df.reference.unique()
ordIts = df.orderItem_no.unique()
ordNos = df.order_no.unique()
transNos = df.transaction_number.unique()
sellerskus = df.seller_sku.unique()
lazada_skus = df.lazada_sku.unique()

print(
    "\nreference:", len(refs), refs,
    "\norderItem_no:", len(ordIts), ordIts,
    "\norderNo:", len(ordNos), ordNos,
    "\ntransaction_number:", len(transNos), transNos,
    "\nsellersku:", len(sellerskus), sellerskus,
    "\nlazada_sku:", len(lazada_skus), lazada_skus,
)

reference: 44 ['683055285636336' '683056460160566' '682933803884800' '683075420632380'
 '682727219414052' '683604323743871' '683580390092228' '683557151377189'
 '683657103904574' '682781438786903' '683893397949360' '683893397849360'
 '683054054966959' '683077041167861' '683076270397897' '682981255445247'
 '683793189608598' '683764158008439' '683830795820207' '683830795920207'
 '683041857909070' '682994240242346' '682994240342346' '682994240142346'
 '683008658308645' '683008658208645' '683008658408645' '682960812496789'
 '682967480041086' '682880825803289' '683734719167225' '683718368370070'
 '683659527672053' '683657104004574' '683659527472053' '683659527572053'
 '682883494068161' '683713989468111' '683732746810983' '683732746910983'
 '683747927422250' '683747927322250' '682887441341977' '682888834134742']
orderItem_no: 45 [nan '683055285636336' '683056460160566' '682933803884800'
 '683075420632380' '682727219414052' '683604323743871' '683580390092228'
 '683557151377189' '683657103904574' '682781438786903' '683893397949360'
 '683893397849360' '683054054966959' '683077041167861' '683076270397897'
 '682981255445247' '683793189608598' '683764158008439' '683830795920207'
 '683830795820207' '683041857909070' '682994240342346' '682994240242346'
 '682994240142346' '683008658408645' '683008658308645' '683008658208645'
 '682960812496789' '682967480041086' '682880825803289' '683734719167225'
 '683718368370070' '683659527672053' '683659527572053' '683659527472053'
 '683657104004574' '682883494068161' '683713989468111' '683732746910983'
 '683732746810983' '683747927422250' '683747927322250' '682887441341977'
 '682888834134742']
orderNo: 33 ['683055285536336' '683056460060566' '682933803784800' '683075420532380'
 '682727219314052' '683604323643871' '683580389992228' '683557150877189'
 '683657103804574' '682781438686903' '683893397749360' '683054054866959'
 '683077041067861' '683076270297897' '682981255345247' '683793189508598'
 '683764157908439' '683830795720207' '683041857809070' '682994240042346'
 '683008658108645' '682960812396789' '682967479941086' '682880825703289'
 '683734719067225' '683718368270070' '683659527372053' '682883493968161'
 '683713989368111' '683732746710983' '683747925422250' '682887441241977'
 '682888834034742']
transaction_number: 84 ['683055285636336' '186108394156336' '683056460160566' '183745588150566'
 '682933803884800' '185206887154800' '683075420632380' '186096386152380'
 '682727219414052' '683604323743871' '683580390092228' '683557151377189'
 '683657103904574' '682781438786903' '683893397949360' '683893397849360'
 '183737603159360' '183737602159360' '683054054966959' '185186471156959'
 '683077041167861' '186519379157861' '683076270397897' '186072164157897'
 '682981255445247' '185166483155247' '683793189608598' '186471972158598'
 '683764158008439' '183593091158439' '683830795820207' '683830795920207'
 '183585761150207' '183585760150207' '683041857909070' '186411719159070'
 '682994240242346' '682994240342346' '682994240142346' '186407209152346'
 '186407208152346' '186407207152346' '683008658308645' '683008658208645'
 '683008658408645' '183509166158645' '183509165158645' '183509164158645'
 '682960812496789' '185888055156789' '682967480041086' '186267243151086'
 '682880825803289' '185856624153289' '683734719167225' '183437131157225'
 '683718368370070' '184914965150070' '683659527672053' '683657104004574'
 '683659527472053' '683659527572053' '682883494068161' '186207308152053'
 '186207307152053' '186207306152053' '185820296154574' '185820295154574'
 '185816698158161' '683713989468111' '185812528158111' '683732746810983'
 '683732746910983' '185788476150983' '185788472150983' '683747927422250'
 '683747927322250' '184874161152250' '184874160152250' '186155512152228'
 '682887441341977' '186123224151977' '682888834134742' '184798255154742']
sellersku: 22 [nan '20250601/1' '20250525/1-Golden Mount Art' '20250506-Brown'
 '20250506-Chili Red' '20250602/1' '20250713/1' '20250626/2'
 '220250927/04' '530164066-Green Floral - Metal-Not Specified'
 '530164066-Green Floral -Velvet-Not Specified'
 '530164066-Blue Floral - Velvet-Not Specified' '20250508-Black-A5'
 '20250528/01-Coffee-A5' '20250508-Coffee-A5' '20250506-Black'
 '20250908/4' '20250727/4-Roll/bangla 300 page-A4'
 '20270727/7-Roll/Bangla 120 Page' '20250727/6-Roll/Bangla 200 Page-A4'
 '20250827/01-Item-02-Other' '20250827/01-Item-10-Other']
lazada_sku: 22 [nan '531411046_BD-2549486307' '531176163_BD-2549240698'
 '529986845_BD-2546835093' '529986845_BD-2546835094'
 '531423209_BD-2549484889' '538522854_BD-2554329035'
 '534781993_BD-2551906335' '529986845_BD-2589405868'
 '530164066_BD-2609049308' '530164066_BD-2609049306'
 '530164066_BD-2609049307' '530254219_BD-2546970371'
 '531288268_BD-2549374488' '530254219_BD-2546970372'
 '529986845_BD-2546835092' '545939119_BD-2581116864'
 '540802174_BD-2558909663' '540785852_BD-2558912598'
 '540810126_BD-2558921217' '545932121_BD-2568137668'
 '545932121_BD-2568137676']

In [32]:
for order_id in ordNos:
    items_per_order = len(df[
        (df["order_no"] == order_id)
        & (df["fee_type"] == "13")
    ])
    if items_per_order > 1:
        print(order_id, items_per_order)

683657103804574 2
683893397749360 2
683830795720207 2
682994240042346 3
683008658108645 3
683659527372053 3
683732746710983 2
683747925422250 2

In [33]:
df[(df["order_no"] == "683657103804574") & (df["fee_type"] == "13")]

            order_no transaction_date  amount paid_status WHT_included_in_amount  payment_ref_id fee_type                   transaction_type        reference                     fee_name WHT_amount transaction_number                  statement comment VAT_in_amount shipping_provider               lazada_sku     orderItem_no orderItem_status shipping_speed          seller_sku                                                                                                                              details shipment_type  Bill Amt  Discount Base
218  683657103804574      06 Jan 2026  1078.0        paid                     No  EFT_SCB_Jan'26       13  Delivered Orders-Delivered Orders  683657104004574  Product Price Paid by Buyer       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  0.00            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping    1078.0            0.0
220  683657103804574      06 Jan 2026  1077.0        paid                     No  EFT_SCB_Jan'26       13  Delivered Orders-Delivered Orders  683657103904574  Product Price Paid by Buyer       0.00    185820295154574  05 Jan 2026 - 11 Jan 2026                  0.00            BD-BPO  529986845_BD-2546835094  683657103904574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping    1077.0            0.0

In [34]:
df[df["reference"] == "683657104004574"]

            order_no transaction_date   amount paid_status WHT_included_in_amount  payment_ref_id fee_type                           transaction_type        reference                                fee_name WHT_amount transaction_number                  statement comment VAT_in_amount shipping_provider               lazada_sku     orderItem_no orderItem_status shipping_speed          seller_sku                                                                                                                              details shipment_type  Bill Amt  Discount Base
184  683657103804574      06 Jan 2026   -24.15        paid                     No  EFT_SCB_Jan'26      114  Services-Logistics & Fulfillment Services  683657104004574                            Handling Fee       0.00    683657104004574  05 Jan 2026 - 11 Jan 2026                  3.15               NaN                      NaN              NaN              NaN            NaN                 NaN                                                                                                                                  NaN           NaN       0.0         -24.15
200  683657103804574      06 Jan 2026  -194.75        paid                     No  EFT_SCB_Jan'26       16          Delivered Orders-Transaction Fees  683657104004574                          Commission Fee       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                 25.40            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping       0.0        -194.75
201  683657103804574      06 Jan 2026   -47.00        paid                     No  EFT_SCB_Jan'26       28          Delivered Orders-Transaction Fees  683657104004574                            Shipping Fee       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  6.13            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping       0.0         -47.00
202  683657103804574      06 Jan 2026   -33.35        paid                     No  EFT_SCB_Jan'26        3          Delivered Orders-Transaction Fees  683657104004574                             Payment Fee       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  4.35            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping       0.0         -33.35
203  683657103804574      06 Jan 2026    47.00        paid                     No  EFT_SCB_Jan'26        8          Delivered Orders-Delivered Orders  683657104004574              Shipping Fee Paid by Buyer       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  0.00            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping       0.0          47.00
218  683657103804574      06 Jan 2026  1078.00        paid                     No  EFT_SCB_Jan'26       13          Delivered Orders-Delivered Orders  683657104004574             Product Price Paid by Buyer       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  0.00            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping    1078.0           0.00
219  683657103804574      06 Jan 2026    -1.05        paid                     No  EFT_SCB_Jan'26     5028          Delivered Orders-Transaction Fees  683657104004574  Daraz Coins Discount Participation Fee       0.00    185820296154574  05 Jan 2026 - 11 Jan 2026                  0.05            BD-BPO  529986845_BD-2546835094  683657104004574        Delivered       standard  20250506-Chili Red  Premium PU Leather Document Folder / Legal Paper Holder / File Organizer for Office, Business & Court Use [Hearts Documents Folder]  Dropshipping       0.0          -1.05

In [26]:
ordNos

array(['683008658108645'], dtype=object)

In [36]:
import json

# order_info = {}

ordNos = df['order_no'].unique()

# for order_id in order_ids:
#     order = discount.get_order(order_id)
#     # request = iop.IopRequest('/order/get', 'GET')

#     # request.add_api_param('access_token', access_token)
#     # request.add_api_param('order_id', order_id)

#     # response = client.execute(request, access_token)

#     # order_data_json = response.body
#     # order = json.loads(order_data_json)["data"]
#     # print(order)
#     order_info[
#         order_id
#     ] = {
#         "created_at": order["created_at"],
#         "retail_price" : order["price"] if "price" in order else None,
#         "voucher" : order["voucher"] if "voucher" in order else 0.0,
#     } 

# order_info

ordItemNos = df['reference'].unique()
# Fetch order info
order_item_info = {}
for order_id in ordNos:
    order_items = discount.get_order_items(order_id)
    for itemDoc in order_items:
        order_item = str(itemDoc.get("order_item_id", None))
        if order_item:
            order_item_info[order_item] = {
                "created_at": itemDoc["created_at"],
                "retail_price": itemDoc.get("item_price", 0.00),
                "voucher": itemDoc.get("voucher_seller", 0.00),
            }

In [39]:
order_item_info_keys = list(order_item_info.keys())

for orderItem_no in order_item_info_keys:
    if orderItem_no not in ordItemNos:
        print(orderItem_no)

# len(order_item_info), len(ordItemNos), order_item_info_keys[0], ordItemNos[0]

683557150977189
683557151077189
683557151177189
683557151277189

In [40]:
# 1️⃣ Clean amount column FIRST
df['amount'] = (
    pd.to_numeric(df['amount'].astype(str).str.replace(',',''), errors='coerce')  # '' or junk → NaN
      .fillna(0)                                  # NaN → 0
)

# define bill amount (only product price rows)
df['Bill Amt'] = np.where(
    df['fee_type'] == "13",
    df['amount'],
    0
)

# define discount base (all others)
df['Discount Base'] = np.where(
    df['fee_type'] != "13",
    df['amount'],
    0
)

In [41]:
# group by order_no
new_df = (
    df.groupby('reference', as_index=False)
    # df.groupby('transaction_number', as_index=False)
    # df.groupby('order_no', as_index=False)
      .agg({
        #   'transaction_number': 'first',
          'order_no': 'first',
          'Bill Amt': 'sum',
          'Discount Base': 'sum',
          'transaction_date': 'last'
      })
)

# rename columns
new_df = new_df.rename(columns={
    'order_no': 'Daraz Bill No.',
    'transaction_date': 'Date'
})

# discount amount = total other amounts × (-1)
new_df['Discount Amt'] = new_df['Discount Base'] * -1

# new_df['Discount Amt'] = (
#     pd.to_numeric(
#         new_df["Discount Amt"], errors='coerce'
#     )
#     .fillna(0)
#     .astype(int)
# )
# new_df['Discount Amt'].fillna(0, inplace=True)
# new_df['Discount Amt'].where('') = 0
# new_df['Discount Amt'] = new_df['Discount Amt'].astype(int)

# received amt

# empty columns
new_df['Payment Amt'] = ''
new_df['Remarks'] = ''
new_df['Bill No.'] = ''
new_df['Order Created At'] = new_df["reference"].apply(lambda x : order_item_info[x]["created_at"])

# new_df["Discount Amt"] = new_df.apply(
#     lambda x : 
#     (
#         x["Discount Amt"]
#         + float(
#             str(
#                 order_info[x["Daraz Bill No."]]["retail_price"]
#                 # order_info[x["Daraz Bill No."]]["voucher"]
#             ).replace(',','')
#         )
#         - x["Bill Amt"]
#     ) if (
#         x["Bill Amt"] != 0.0
#     )
#     else x["Discount Amt"]
#     , 
#     axis=1
# )

# new_df["Discount Amt"] = new_df["Discount Amt"].round(2)

# new_df["Bill Amt"] = new_df.apply(
#     lambda x : 
#     float(order_info[x["Daraz Bill No."]]["retail_price"]) 
#     if (
#         # (float(x["Bill Amt"]) != float(order_info[x["Daraz Bill No."]]["retail_price"]))
#         (float(order_info[x["Daraz Bill No."]]["voucher"]) != 0.0 )
#         and (x["Bill Amt"] != 0.0)
#     )
#     else x["Bill Amt"], 
#     axis=1
# )

# for ord_id in ordNos:
#     retail_price_total = float(new_df[new_df["Daraz Bill No."] == ord_id]["Bill Amt"].sum())
#     before_seller_discount = float(order_info[ord_id]["retail_price"])
#     discount = round(float(before_seller_discount - retail_price_total), 2)
#     idx = new_df[
#         new_df["Daraz Bill No."] == ord_id
#     ].index[0]
#     if new_df.loc[idx, "Bill Amt"] != 0:
#         new_df.loc[ 
#             idx, 
#             ["Bill Amt", "Discount Amt"]
#         ] += [discount, discount]

for ordItemNo in ordItemNos:
    if ordItemNo in order_item_info:
        retail_price = order_item_info[ordItemNo]["retail_price"]
        voucher = order_item_info[ordItemNo]["voucher"]
        idx = new_df[new_df['reference'] == ordItemNo].index[0]
        if new_df.loc[idx, 'Bill Amt'] != 0:
            new_df.loc[idx, 'Bill Amt'] = retail_price
            new_df.loc[idx, 'Discount Amt'] += voucher

new_df['Received Amt'] = new_df['Bill Amt'] - new_df['Discount Amt']

new_df['Received Amt'] = new_df['Received Amt'].round(2)

print(
    type(new_df["Discount Amt"][0]),
    type(new_df["Bill Amt"][0]),
    type(new_df["Received Amt"][0]),
)
# drop helper column
new_df = new_df.drop(columns=['Discount Base'])

new_df = new_df[[
    'Order Created At', 'Date', 'Payment Amt', 'Bill No.', 
    # 'transaction_number',
    # 'reference',
    'Daraz Bill No.', 'Bill Amt', 'Received Amt', 'Discount Amt', 'Remarks'
]]

<class 'numpy.float64'> <class 'numpy.float64'> <class 'numpy.float64'>

In [43]:
new_df = new_df.sort_values(
    by=[
        'Order Created At',
        # 'Daraz Bill No.',
        # 'Date', 
    ],
    ascending=[
        False, 
        # False, 
        # False
    ],
).reset_index(drop=True)

In [44]:
new_df[[
    'Bill Amt',
    'Received Amt', 
    'Discount Amt', 
]].sum()

Bill Amt        20115.00
Received Amt    14853.11
Discount Amt     5261.89
dtype: float64

In [45]:
new_df

             Order Created At         Date Payment Amt Bill No.   Daraz Bill No.  Bill Amt  Received Amt  Discount Amt Remarks
0   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360     190.0        137.67         52.33
1   2026-01-10 16:15:04 +0800  11 Jan 2026                       683893397749360     190.0        137.67         52.33
2   2026-01-09 20:30:19 +0800  11 Jan 2026                       683076270297897     160.0        114.68         45.32
3   2026-01-09 20:21:56 +0800  11 Jan 2026                       683077041067861     160.0        114.68         45.32
4   2026-01-09 19:13:23 +0800  11 Jan 2026                       683075420532380     160.0        111.89         48.11
5   2026-01-09 01:19:22 +0800  11 Jan 2026                       683056460060566     220.0        182.34         37.66
6   2026-01-09 00:59:11 +0800  11 Jan 2026                       683055285536336     160.0        114.68         45.32
7   2026-01-08 23:55:56 +0800  11 Jan 2026                       683054054866959     385.0        280.80        104.20
8   2026-01-08 17:22:51 +0800  09 Jan 2026                       683041857809070    1099.0        816.28        282.72
9   2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207     190.0        137.67         52.33
10  2026-01-08 03:52:26 +0800  10 Jan 2026                       683830795720207     190.0        137.67         52.33
11  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     240.0        167.84         72.16
12  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     240.0        167.09         72.91
13  2026-01-07 14:21:39 +0800  08 Jan 2026                       683008658108645     240.0        167.84         72.16
14  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     185.0        127.80         57.20
15  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     185.0        127.80         57.20
16  2026-01-06 23:40:31 +0800  09 Jan 2026                       682994240042346     185.0        127.05         57.95
17  2026-01-06 23:36:31 +0800  10 Jan 2026                       683793189508598    1099.0        841.26        257.74
18  2026-01-06 16:01:56 +0800  11 Jan 2026                       682981255345247    1099.0        841.26        257.74
19  2026-01-06 01:44:59 +0800  07 Jan 2026                       682967479941086     240.0        172.04         67.96
20  2026-01-06 00:57:59 +0800  10 Jan 2026                       683764157908439     317.0        245.43         71.57
21  2026-01-05 22:50:35 +0800  07 Jan 2026                       682960812396789     419.0        306.30        112.70
22  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250     250.0        194.60         55.40
23  2026-01-05 16:51:53 +0800  06 Jan 2026                       683747925422250     250.0        194.60         55.40
24  2026-01-05 04:43:40 +0800  06 Jan 2026                       683734719067225    1088.0        832.58        255.42
25  2026-01-05 03:18:08 +0800  11 Jan 2026                       682933803784800    1088.0        832.58        255.42
26  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983    1088.0        832.57        255.43
27  2026-01-05 02:42:01 +0800  06 Jan 2026                       683732746710983    1088.0        832.57        255.43
28  2026-01-04 20:40:21 +0800  06 Jan 2026                       683718368270070     590.0        466.65        123.35
29  2026-01-04 18:58:33 +0800  06 Jan 2026                       683713989368111     240.0        172.04         67.96
30  2026-01-03 21:12:36 +0800  05 Jan 2026                       682888834034742     419.0        297.60        121.40
31  2026-01-03 20:39:20 +0800  05 Jan 2026                       682887441241977     159.0        113.91         45.09
32  2026-01-03 20:36:07 +0800  06 Jan 2026                       682883493968161    1088.0        807.61        280.39
33  2026-01-03 17:23:14 +0800  07 Jan 2026                       682880825703289     159.0        111.14         47.86
34  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053     680.0        491.84        188.16
35  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053     610.0        440.10        169.90
36  2026-01-02 23:16:07 +0800  06 Jan 2026                       683659527372053     490.0        354.30        135.70
37  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574    1088.0        824.70        263.30
38  2026-01-02 21:49:12 +0800  06 Jan 2026                       683657103804574    1088.0        798.02        289.98
39  2026-01-01 01:58:30 +0800  11 Jan 2026                       683604323643871       0.0        -34.50         34.50
40  2025-12-31 16:18:38 +0800  05 Jan 2026                       683580389992228    1099.0        818.26        280.74
41  2025-12-31 14:13:58 +0800  11 Jan 2026                       682781438686903       0.0        -23.00         23.00
42  2025-12-30 16:56:25 +0800  11 Jan 2026                       683557150877189       0.0        -59.80         59.80
43  2025-12-29 16:39:13 +0800  11 Jan 2026                       682727219314052       0.0        -23.00         23.00

# other

In [ ]:
base_url = "https://api.daraz.com.bd/rest"
url= base_url + "/finance/transaction/details/get"

client = iop.IopClient(url, appkey ,appSecret)
request = iop.IopRequest('/seller/metrics/get','GET')
response = client.execute(request, access_token)
print(response.type)
print(response.body)